### ISSUE TITLE
tag recordings

### ISSUE THREAD

**Issue by Hauwertlhaufn** [dkim0419/SoundRecorder#16]
Tags for recordings would be nice.
So you would be able to filter f.ex. between private- and business-recordings.

**Comment by babarbaig92** [comment]
Hi, I am trying to add this functionality. I have created a new table in DBHelper.java class. Added a new fragment that opens up a dialog and takes text of tag from user. From that fragment I am calling DBHelper function that adds this input into DB. This gives me error NullException. Error is as follow. Please help me solve the issue. 

11-25 10:10:17.116  16326-16326/com.danielkim.soundrecorder E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at com.danielkim.soundrecorder.DBHelper.addTag(DBHelper.java:177)
            at com.danielkim.soundrecorder.fragments.AddTagFragment$2.onClick(AddTagFragment.java:48)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
            at dalvik.system.NativeStart.main(Native Method)
